{% set name = "geograpy3" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geograpy3-{{ version }}.tar.gz
  sha256: 7bbbba7cc249638f96e70e625b0cc1128d93e405653280d7136b3837ba83ffb3

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - jellyfish
    - newspaper3k
    - nltk
    - numpy
    - pandas
    - pylodstorage
    - python >=3.6
    - scikit-learn
    - sphinx_rtd_theme

test:
  imports:
    - geograpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/somnathrakshit/geograpy3
  summary: Extract countries, regions and cities from a URL or text
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cml37
